namespace HighLoadDevelopment.Enums
{
    public enum PermissionsNames
    {
        get_list_user,
        get_list_role,
        get_list_permission,
        read_user,
        read_role,
        read_permission,
        create_user,
        create_role,
        create_permission,
        update_user,
        update_role,
        update_permission,
        delete_user,
        delete_role,
        delete_permission,
        restore_user,
        restore_role,
        restore_permission,
        get_story_user,
        get_story_role,
        get_story_permission,
        rollback_permission,
        rollback_role,
        get_files
    }
}
